```mermaid
graph LR
subgraph "App"
    AppRoutingModule --> AppComponent
    AppRoutingModule --> NavbarComponent
end

subgraph "Tasks"
    TasksModule --> TaskListComponent
    TasksModule --> TaskItemComponent
    TasksModule --> TaskDetailsComponent
    TaskDetailsService --> TaskService
    TaskDetailsService --> NotificationService
end

subgraph "Components"
    AppComponent --> NavbarComponent
    NavbarComponent --> TaskListComponent
    TaskListComponent --> TaskItemComponent
    TaskItemComponent --> TaskDetailsComponent
end

NotificationService --> TaskDetailsService
TaskService --> TaskDetailsComponent